---
- hosts: webservers
  become: yes
  tasks:
  - name: i want to know host name
    command: hostame -f
    register: myresult

  - name: display myresult value
    debug: 
      msg: "{{myresult}}"